name: 🛠️ Build

on:
  workflow_call:
    inputs:
      notarize:
        type: boolean
        default: false

    secrets:
      FASTLANE_KEYCHAIN_PASSWORD:
        required: true
      MATCH_GIT_PRIVATE_KEY:
        required: true
      MATCH_PASSWORD:
        required: true

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      # Needed for fastlane
      - name: Setup Ruby
        uses: ruby/setup-ruby@d354de180d0c9e813cfddfcbdc079945d4be589b # v1.275.0
        with:
          ruby-version: 3.4.8
          bundler-cache: true

      - name: "Import certificate and profile"
        run: bundle exec fastlane prepare_signing
        env:
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

      - name: Build app
        run: |
          xcodebuild build \
              -project SentryReplayDebugger.xcodeproj \
              -scheme SentryReplayDebugger \
              -configuration Release \
              -destination 'generic/platform=macOS' \
              PRODUCT_BUNDLE_IDENTIFIER="io.sentry.SentryReplayDebugger" \
              CODE_SIGN_IDENTITY="Developer ID Application" \
              CODE_SIGN_STYLE=Manual \
              PROVISIONING_PROFILE_SPECIFIER="match Direct io.sentry.SentryReplayDebugger macos" \
              DEVELOPMENT_TEAM="97JCY7859U"

      - name: Create app zip
        run: |
          cd ~/Library/Developer/Xcode/DerivedData/SentryReplayDebugger-*/Build/Products/Release
          zip -r --symlinks "${{ github.workspace }}/SentryReplayDebugger.zip" SentryReplayDebugger.app

      - name: Notarize app bundle
        if: inputs.notarize
        run: |
          echo "::warning::Not implemented yet"

      - name: Upload app bundle
        uses: actions/upload-artifact@v6
        with:
          name: ${{ github.sha }}
          path: SentryReplayDebugger.zip
