name: Changelog Preview
permissions:
  contents: read
  pull-requests: write
secrets: inherit
on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@v2
    secrets: inherit
