name: ⚙️ CI

on:
  push:
    branches:
      - "main"
      - "release/**"
    paths-ignore:
      - "*.md"

  pull_request:
    paths-ignore:
      - "*.md"

# Cancel in-progress runs on PR update and on push.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: 🛠️ Build app
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Build app
        run: |
          xcodebuild -project SentryReplayDebugger.xcodeproj \
              -scheme SentryReplayDebugger \
              -configuration Release \
              CODE_SIGNING_ALLOWED=NO \
              -destination 'platform=macOS,arch=arm64' \
              build

  test:
    name: 🧪 Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run tests
        run: |
          xcodebuild -project SentryReplayDebugger.xcodeproj \
              -scheme SentryReplayDebugger \
              -configuration Debug \
              CODE_SIGNING_ALLOWED=NO \
              -destination 'platform=macOS,arch=arm64'
              test
