name: 🧪 Test

on:
  workflow_call:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: 🧪 Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Run tests
        run: |
          xcodebuild test \
              -project SentryReplayDebugger.xcodeproj \
              -scheme SentryReplayDebugger \
              -configuration Debug \
              -destination 'platform=macOS,arch=arm64' \
              -only-testing:SentryReplayDebuggerTests \
              CODE_SIGNING_ALLOWED=NO
